# https://likegeeks.com/linux-ldap-server/
# by nic garner
# install config
#
---
- name: install ldap tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openldap
    - openldap-clients
    - openldap-servers

- name: enable ldap
  service: 
    name: slapd
    state: started 
    enabled: yes

#- name: setldap password
#  command: ldappassword

