# configures nicgarner.info
# by Nic Garner
#
---
- name: copy website data
  copy: 
    src: dev/nicgarner.info/
    dest: /var/www/nicgarner.info/public_html/
    owner: www-data
    group: www-data
    mode: 0755


