# installs and sets the basic configuration for httpd
# by Nic Garner
#
---
- name: install httpd
  package:
    name: httpd
    state: present

- name: enable httpd
  service:
    name: httpd
    enabled: yes

# notify: restart_httpd
