# handlers for ansible
# by nic garner
# this should work for all playbooks
#
---
# Restart CSF
- name: restart_csf
  service:
    name: csf
    state: restarted

- name: restart_lfd
  service: 
    name: lfd
    state: restarted
